<?php

// 所有管理文件所使用的语言定义
// 简体中文 作者 reishi https://reishi.cc
$lang_admin_bans = array(

'Ban advanced'					=>	'高级封禁设置',
'Ban advanced heading'			=>	'通过用户名、IP 及邮箱进行组合封禁，或单独针对 IP/邮箱进行封禁',
'Ban criteria legend'			=>	'封禁条件',
'Ban settings legend'			=>	'封禁设置',
'Ban IP warning'				=>	'<strong>请注意！</strong> 封禁 IP 段时务必谨慎，因为该操作极有可能会误伤到使用相同核心 IP 的其他无辜用户',
'Current ban head'				=>	'操作人："%s"',
'Username'						=>	'用户名',
'Username to ban label'			=>	'要封禁的用户名',
'Ban creator'					=>	'执行封禁的管理员',
'IP-addresses to ban label'		=>	'要封禁的 IP 地址',
'IP-addresses help'				=>	'请输入您要封禁的 IP 或 IP 段（例如 150.11.110.1 或 150.11.110），多个地址请用空格隔开。如果此处已输入 IP，则为该用户在数据库中最后一次登录的已知 IP',
'IP-addresses help stats'		=>	'点击下方链接查看该用户的 IP 统计数据',
'IP-addresses help link'		=>	'用户 IP 统计',
'E-mail/domain to ban label'	=>	'要封禁的邮箱或域名',
'E-mail/domain help'			=>	'请输入您要封禁的邮箱或邮箱后缀域名（例如 someone@example.com 或 example.com）。更多信息请参考“设置/注册”中的“允许使用已封禁的邮箱注册”',
'Ban message label'				=>	'封禁提示信息',
'Ban message help'				=>	'该用户访问论坛时将看到的提示信息',
'Expire date label'				=>	'封禁到期时间',
'Expire date help'				=>	'封禁自动解除的日期（格式：YYYY-MM-DD）。如需手动解除请留空',
'Expires'						=>	'到期时间',
'Message'						=>	'提示信息',
'New ban heading'				=>	'封禁指定用户名',
'New ban legend'				=>	'添加封禁',
'Advanced ban info'				=>	'下一页您可以输入自定义的 IP 和邮箱。如果您只想单纯封禁某个 IP/IP 段或邮箱，请将本页的用户名留空',
'Existing bans heading'			=>	'管理或解除现有的封禁',
'Add ban'						=>	'添加封禁',
'Save ban'						=>	'保存封禁',
'E-mail'						=>	'电子邮箱',
'IP-ranges'						=>	'IP/IP 段',
'Reason'						=>	'封禁原因',
'No bans'						=>	'封禁列表为空',
'Edit ban'						=>	'修改封禁',
'Remove ban'					=>	'解除封禁',
'Edit or remove'				=>	'"%s" 或 "%s"',
'Ban removed'					=>	'封禁已解除',
'Ban added'						=>	'封禁已生效',
'Ban edited'					=>	'封禁信息已更新',
'No user id message'			=>	'未找到该 ID 对应的注册用户',
'No user username message'		=>	'未找到该用户名对应的注册用户。如果您想进行不针对特定用户的封禁，请将用户名留空',
'User is admin message'			=>	'该用户为系统管理员，无法直接封禁。如果您确实需要封禁该管理员，请先将其移至其他用户组',
'Must enter message'			=>	'请至少填写以下一项信息：用户名、IP 地址或电子邮箱',
'Invalid IP message'			=>	'您输入的 IP 或 IP 段格式不正确',
'Can\'t ban guest user'			=>	'无法封禁游客系统账户',
'Invalid e-mail message'		=>	'您输入的邮箱（如 user@example.com）或邮箱后缀域名（如 example.com）格式不正确',
'Invalid expire message'		=>	'到期日期格式不正确。正确格式为 YYYY-MM-DD，且到期时间至少要在明天之后',


);