<?php

$lang_admin_settings = array(

'Settings updated'				=>	'全局设置已成功更新',

// Setup section
'Setup personal'				=>	'打造属于您自己的 PunBB 论坛个性化配置',
'Setup personal legend'			=>	'论坛基本信息',
'Board description label'		=>	'站点简介描述',
'Board title label'				=>	'站点名称/标题',
'Default style label'			=>	'系统默认模板风格',
'Setup local'					=>	'针对您所在的地区配置本地化环境',
'Setup local legend'			=>	'区域与时间设置',
'Default timezone label'		=>	'默认时区',
'DST label'						=>	'开启夏令时（自动将时间提前 1 小时）',
'Default language label'		=>	'默认语言包',
'Default language help'			=>	'（如果您删除了某个语言包，请务必及时同步更新此处的设置）',
'Time format label'				=>	'时间显示格式',
'Date format label'				=>	'日期显示格式',
'Current format'				=>	'[ 当前格式：%s ] %s',
'External format help'			=>	'具体的格式化参数选项可参考 PHP 官方 date 函数说明页面',
'Setup timeouts'				=>	'配置系统的默认超时时间与跳转延迟',
'Setup timeouts legend'			=>	'超时与重定向设置',
'Visit timeout label'			=>	'登录会话超时',
'Visit timeout help'			=>	'用户无操作多少秒后系统将自动强制注销其登录状态',
'Online timeout label'			=>	'在线状态保持',
'Online timeout help'			=>	'用户无操作多少秒后将从当前在线用户列表中移除',
'Redirect time label'			=>	'提示页跳转延迟',
'Redirect time help'			=>	'如果设置为 0 秒，系统将直接执行跳转而不显示任何过渡性的重定向提示页面',
'Setup pagination'				=>	'配置主题列表、帖子内容及帖子预览的默认每页显示行数',
'Setup pagination legend'		=>	'分页加载默认值',
'Topics per page label'			=>	'每页显示主题数',
'Posts per page label'			=>	'每页显示帖子数',
'Topic review label'			=>	'发帖时预览历史回复数',
'Topic review help'				=>	'按发布时间由新到旧排序，设置为 0 则关闭此预览功能',
'Setup reports'					=>	'配置接收用户举报帖子与主题的通知渠道',
'Setup reports legend'			=>	'举报接收配置',
'Reporting method'				=>	'通知接收方式',
'Report internal label'			=>	'仅通过论坛后台内置的举报管理系统接收',
'Report both label'				=>	'同时通过后台内置举报系统以及发送电子邮件给通知列表中的管理员',
'Report email label'			=>	'仅向通知列表中的管理员发送电子邮件通知',
'Setup URL'						=>	'配置您论坛页面的 URL 伪静态规则（搜索引擎友好型 SEF 网址）',
'Setup URL legend'				=>	'选择 URL 伪静态方案',
'URL scheme info'				=>	'<strong>请注意！</strong> 托管本论坛的服务器必须支持并开启 mod_rewrite 模块，且必须允许使用 <em>.htaccess</em> 分布式配置文件。如果您使用的是 Apache 以外的 Web 服务器（如 Nginx），请参考相关服务器的规则配置说明',
'URL scheme label'				=>	'URL 伪静态方案',
'URL scheme help'				=>	'请确保您已仔细阅读并完全理解了上述说明信息',
'Setup links'					=>	'向论坛的主导航菜单中添加自定义链接',
'Setup links info'				=>	'通过在此文本框中直接输入 HTML 超链接代码，您可以向所有页面顶部的导航菜单中自由添加任意自定义项目。添加格式为 X = &lt;a href="URL"&gt;链接文字&lt;/a&gt;，其中 X 代表链接插入的具体排序位置（例如输入 0 代表插入到导航最前列，输入 2 代表插入到“用户列表”后面）。多个链接项目请换行分隔',
'Setup links legend'			=>	'自定义菜单项',
'Enter links label'				=>	'输入您的自定义链接代码',
'Error no board title'			=>	'请输入站点标题',
'Error timeout value'			=>	'“在线状态保持”的超时秒数必须小于“登录会话超时”的秒数',


// Features section
'Features general'				=>	'配置可自由选择开启的论坛常规功能组件',
'Features general legend'		=>	'常规功能开关',
'Searching'						=>	'全局搜索',
'Search all label'				=>	'允许用户一次性搜索所有版块而非只能逐个版块进行搜索。如果论坛因搜索频繁导致服务器负载过高，建议关闭此项',
'User ranks'					=>	'会员等级',
'User ranks label'				=>	'允许根据用户的发帖数量计算并展示对应的等级头衔',
'Censor words'					=>	'敏感词过滤',
'Censor words label'			=>	'开启对特定词汇的敏感词审查替换功能',
'Quick jump'					=>	'版块快速导航',
'Quick jump label'				=>	'在页面底部显示用于快速跳转版块的下拉菜单',
'Show version'					=>	'显示系统版本',
'Show version label'			=>	'在页面底部的页脚中展示当前 PunBB 的版本号',
'Show moderators'				=>	'显示版主列表',
'Show moderators label'			=>	'在论坛首页的版块列表中直接展示负责管理的版主名单',
'Online list'					=>	'在线列表',
'Users online label'			=>	'在论坛首页展示当前在线的游客与注册会员列表',
'Features posting'				=>	'配置主题与帖子的发布功能及相关信息展示',
'Features posting legend'		=>	'互动发帖配置',
'Quick post'					=>	'快速发帖/快速回复',
'Quick post label'				=>	'在主题帖子的正文下方直接显示一个简易的快速回复框',
'Subscriptions'					=>	'主题关注与订阅',
'Subscriptions label'			=>	'允许会员关注并订阅指定主题（当有新回复时用户将收到邮件提醒）',
'Guest posting'					=>	'游客发帖限制',
'Guest posting label'			=>	'强制要求未登录的游客在发帖时必须填写电子邮箱地址',
'User has posted'				=>	'已参与主题标记',
'User has posted label'			=>	'在主题列表前方显示一个小圆点，用于提示当前用户此前曾参与过该主题的讨论。如果您的服务器负载过高，建议关闭此功能',
'Topic views'					=>	'主题浏览量统计',
'Topic views label'				=>	'实时统计并记录主题的浏览点击次数。在高并发或繁忙的论坛中若遇到服务器压力过大，建议关闭此项',
'User post count'				=>	'用户发帖计数',
'User post count label'			=>	'在帖子详情页、个人资料页以及会员列表中展示用户的总发帖量',
'User info'						=>	'帖子内展示用户信息',
'User info label'				=>	'在帖子左侧的用户信息栏中展示发帖人的来自地区、注册日期、发帖量、邮箱以及个人网站链接',
'Features posts'				=>	'主题与帖子内容展示规则',
'Features posts legend'			=>	'帖子内容渲染选项',
'Post content group'			=>	'内容解析选项',
'Allow BBCode label'			=>	'允许在帖子中使用 BBCode 标签代码（推荐开启）',
'Allow img label'				=>	'允许在帖子中通过 BBCode 使用 [img] 标签插入外部图片',
'Smilies in posts label'		=>	'自动将帖子中的文本表情符号转换为对应的小图标',
'Make clickable links label'	=>	'允许 BBCode 解析器自动识别内容中的纯文本 URL 网址并自动为其套上 [url] 超链接标签',
'Allow capitals group'			=>	'允许全大写字母',
'All caps message label'		=>	'允许帖子正文内容全部由大写英文字母组成',
'All caps subject label'		=>	'允许主题标题内容全部由大写英文字母组成',
'Indent size label'				=>	'[code] 代码块缩进大小',
'Indent size help'				=>	'设置代码块内文本缩进所占用的空格数。如果设置为 8，则将直接使用标准的 Tab 制表符进行缩进',
'Quote depth label'				=>	'引用回复最大嵌套层数',
'Quote depth help'				=>	'设置 [quote] 引用标签内允许叠加嵌套其他引用标签的最大层数，超出此深度的嵌套内容将被系统直接过滤丢弃',
'Features sigs'					=>	'用户个性签名及内容规则',
'Features sigs legend'			=>	'个人签名选项',
'Allow signatures'				=>	'启用个人签名',
'Allow signatures label'		=>	'允许会员在发布的帖子下方附加展示其个人设置的签名内容',
'Signature content group'		=>	'签名内容权限',
'BBCode in sigs label'			=>	'允许在个性签名中使用 BBCode 标签代码',
'Img in sigs label'				=>	'允许在个性签名中通过 [img] 标签插入图片（出于版面美观考虑，通常不推荐开启）',
'All caps sigs label'			=>	'允许个性签名内容全部由大写英文字母组成',
'Smilies in sigs label'			=>	'自动个性签名中的文本表情符号转换为对应的小图标',
'Max sig length label'			=>	'个性签名最大允许字符数',
'Max sig lines label'			=>	'个性签名最大允许行数',
'Features Avatars'				=>	'用户头像上传及尺寸规范设置',
'Features Avatars legend'		=>	'会员头像设置',
'Allow avatars'					=>	'启用自定义头像',
'Allow avatars label'			=>	'允许用户上传个性化头像并在发表的帖子旁展示',
'Avatar directory label'		=>	'头像上传存储目录',
'Avatar directory help'			=>	'此路径相对于 PunBB 的根目录。请确保 PHP 环境对该目录拥有绝对的可写写入权限',
'Avatar Max width label'		=>	'头像最大允许宽度',
'Avatar Max width help'			=>	'像素值（推荐设为 60）',
'Avatar Max height label'		=>	'头像最大允许高度',
'Avatar Max height help'		=>	'像素值（推荐设为 60）',
'Avatar Max size label'			=>	'头像文件最大体积',
'Avatar Max size help'			=>	'字节数（推荐设为 15360，即 15KB）',
'Features update'				=>	'系统自动检查更新机制',
'Features update info'			=>	'PunBB 能够定期自动为您检测软件是否存在重要的版本更新或官方发布的热补丁。当有可用更新时，系统会在管理后台向管理员发出系统提示',
'Features update disabled info'	=>	'当前的服务器环境暂不支持自动检查更新功能。要激活此特性，PunBB 运行所需的 PHP 环境必须支持并开启 <a href="http://www.php.net/manual/en/ref.curl.php">cURL 扩展</a>、<a href="http://www.php.net/manual/en/function.fsockopen.php">fsockopen() 函数</a>，或者在配置中将 <a href="http://www.php.net/manual/en/ref.filesystem.php#ini.allow-url-fopen">allow_url_fopen</a> 设为开启状态',
'Features update legend'		=>	'自动更新检查',
'Update check'					=>	'自动检查更新',
'Update check label'			=>	'开启后台自动检测版本升级功能',
'Check for versions'			=>	'检测扩展升级',
'Auto check for versions'		=>	'允许系统自动检测已安装插件扩展是否有新版本发布',

'Features mask passwords'			=>	'表单密码掩码遮蔽保护',
'Features mask passwords legend'	=>	'密码可见性控制',
'Features mask passwords info'		=>	'如果开启，PunBB 将遮蔽处理所有表单中的密码输入框，并在需要时展示二次密码确认文本框。如果关闭，密码输入框将以明文呈现，且用户在注册或修改密码时只需输入一次即可。需要注意的是，登录表单中的密码框出于绝对安全考量，将始终强制进行小黑点遮蔽（不受此选项控制）',
'Enable mask passwords'				=>	'开启密码遮蔽',
'Enable mask passwords label'		=>	'在常规表单中对密码字段启用隐藏遮蔽',

'Features gzip'					=>	'利用 gzip 页面压缩输出',
'Features gzip legend'			=>	'输出流压缩方案',
'Features gzip info'			=>	'开启后，PunBB 将利用 gzip 压缩发送给浏览器的网页数据。这能显著降低网络带宽消耗，但会略微增加服务器 CPU 的开销。该特性要求您的 PHP 环境编译了 zlib 库（--with-zlib）。注意：如果您的 Web 服务器（如 Apache 或 Nginx）已经在底层配置了 mod_gzip 或 mod_deflate 等模块来压缩 PHP 脚本，请务必关闭此选项',
'Enable gzip'					=>	'开启 gzip 压缩',
'Enable gzip label'				=>	'启用基于 gzip 的网页输出流压缩优化',

// Announcements section
'Announcements head'			=>	'在论坛的所有页面上方发布并展示全局系统公告',
'Announcements legend'			=>	'全局公告管理',
'Enable announcement'			=>	'启用全局公告',
'Enable announcement label'		=>	'在论坛顶部前台展示公告信息内容',
'Announcement heading label'	=>	'公告标题',
'Announcement message label'	=>	'公告正文内容',
'Announcement message help'		=>	'公告正文支持直接使用 HTML 代码，系统不会像对常规帖子那样对其进行严格的排版解析限制',
'Announcement message default'	=>	'<p>请在此处输入您的公告正文内容</p>',

// Registration section
'Registration new'				=>	'新用户注册控制规则',
'New reg info'					=>	'您可以自由选择是否对所有新注册的用户进行邮箱激活验证。开启注册验证后，用户在提交注册时会收到一封包含激活链接的电子邮件，他们必须点击该链接才能设置登录密码并成功登录。此外，开启此功能后，会员若想更改在个人资料中绑定的电子邮箱，也必须对新邮箱进行相同的验证。这是防范恶意注册滥用论坛以及确保所有会员个人资料中留有“真实有效”联系方式的有力手段',
'Registration new legend'		=>	'新用户注册设置',
'Allow new reg'					=>	'开放新用户注册',
'Allow new reg label'			=>	'允许新会员提交注册申请。通常仅在网站遇到特殊维护或紧急状况时才考虑关闭此项',
'Verify reg'					=>	'强制邮箱验证',
'Verify reg label'				=>	'要求所有新注册的账号必须通过电子邮件激活链接完成验证',
'Reg e-mail group'				=>	'注册邮箱规范',
'Allow banned label'			=>	'允许使用已被系统列入封禁黑名单的邮箱或后缀进行注册',
'Allow dupe label'				=>	'允许不同的账号重复使用同一个电子邮箱地址进行注册',
'Report new reg'				=>	'新注册邮件通知',
'Report new reg label'			=>	'每当有新用户成功注册入驻时，自动向邮件通知列表中的管理员发送提醒邮件',
'E-mail setting group'			=>	'默认隐私公开设置',
'Display e-mail label'			=>	'默认对其他会员公开展示自己的电子邮箱地址',
'Allow form e-mail label'		=>	'隐藏真实邮箱地址，但允许其他会员通过论坛内置的内置邮件表单给自己写信',
'Disallow form e-mail label'	=>	'完全隐藏真实邮箱地址，且彻底禁止其他会员通过论坛给自己发送任何邮件',
'Registration rules'			=>	'论坛服务协议与社区规范规则（启用并撰写站点规则）',
'Registration rules info'		=>	'您可以要求新用户在提交注册前必须勾选并同意一套社区规范协议。该协议内容将始终作为固定链接展现在每个页面顶部的导航菜单中。您可以在下方开启此功能并自由撰写具体协议条文',
'Registration rules legend'		=>	'注册服务协议',
'Require rules'					=>	'启用注册规范协议',
'Require rules label'			=>	'新用户在注册账号前必须强制阅读并点击同意论坛协议',
'Compose rules label'			=>	'编辑协议条文正文内容',
'Compose rules help'			=>	'文本区域支持直接编写 HTML 代码，系统不会对其做任何排版解析过滤',
'Rules default'					=>	'请在此处输入您的论坛社区规范与服务协议具体内容',

// Email section
'E-mail addresses'				=>	'论坛官方系统邮箱及管理员收信列表配置',
'E-mail addresses legend'		=>	'系统电子邮箱设置',
'Admin e-mail'					=>	'超级管理员联系邮箱',
'Webmaster e-mail label'		=>	'发信人邮箱（Webmaster）',
'Webmaster e-mail help'			=>	'由论坛系统向外发送任何自动邮件时（如激活信、密码找回信）所展示的 From 发件人地址',
'Mailing list label'			=>	'管理员通知发信列表',
'Mailing list help'				=>	'用于接收用户举报信息或新用户注册通知的管理员邮箱列表，多个邮箱请用英文半角逗号分隔',
'E-mail server'					=>	'用于从论坛向外投递电子邮件的外部/本地邮件服务器配置',
'E-mail server legend'			=>	'发信服务器（SMTP）配置',
'E-mail server info'			=>	'通常情况下，PunBB 能够顺畅调用您本地服务器自带的 mail 程序发信，此时您可以完全忽略以下设置。如果您希望配置 PunBB 使用更加稳定的外部第三方邮件服务器发信，请在此输入外部服务器的地址；若该 SMTP 服务器使用的不是默认的 25 端口，请务必指定自定义端口号（例如：mail.example.com:3580）',
'SMTP address label'			=>	'SMTP 服务器地址',
'SMTP address help'				=>	'使用外部邮件服务时填写。如果希望留空则默认调用本地服务器自带的发信程序',
'SMTP username label'			=>	'SMTP 认证账号用户名',
'SMTP username help'			=>	'绝大多数外部 SMTP 发信服务均需要填写，若本地发信一般无需填写',
'SMTP password label'			=>	'SMTP 认证账号密码/授权码',
'SMTP password help'			=>	'绝大多数外部 SMTP 发信服务均需要填写，若本地发信一般无需填写',
'SMTP SSL'						=>	'开启 SMTP 传输加密（SSL/TLS）',
'SMTP SSL label'				=>	'当您的 PHP 环境支持 SSL 组件且您的外部 SMTP 服务器强制要求安全加密连接时请开启此项',
'Error invalid admin e-mail'	=>	'您输入的超级管理员联系邮箱格式不正确',
'Error invalid web e-mail'		=>	'您输入的发信人邮箱格式不正确',

// Maintenance section
'Maintenance head'				=>	'撰写闭站维护公告并一键激活论坛维护模式',
'Maintenance mode info'			=>	'<strong>重要提示！</strong> 将站点切换至维护模式意味着整个论坛前台将暂时关闭，届时仅有拥有最高权限的超级管理员能够正常登录并访问。通常在网站进行程序升级、迁移或紧急数据维护时使用',
'Maintenance mode warn'			=>	'<strong>安全警告！</strong> 在处于闭站维护模式期间，请<strong>千万不要注销退出您的管理员账号</strong>。否则，您自己也将无法再次登录回后台',
'Maintenance legend'			=>	'站点维护控制',
'Maintenance mode'				=>	'闭站维护模式',
'Maintenance mode label'		=>	'立即将当前论坛强行切换至闭站维护状态',
'Maintenance message label'		=>	'维护状态提示语',
'Maintenance message help'		=>	'论坛处于维护模式时展示给普通访问者的提示信息。您可以在文本框中自由使用 HTML 代码来美化排版',
'Maintenance message default'	=>	'论坛目前正在进行例行数据维护，前台服务暂时关闭。请在几分钟后重试，感谢您的理解与配合。<br /><br />网站管理团队',

);