<?php

// 后台版块管理所使用的语言定义
// 简体中文 作者 reishi https://reishi.cc
$lang_admin_forums = array(

'Edit forum head'				=>	'编辑版块：%s',
'Edit or delete'				=>	'%s 或 %s',
'Edit'							=>	'编辑',
'Delete'						=>	'删除',
'Forum name'					=>	'版块名称',
'Position label'				=>	'显示排序',
'Delete forum'					=>	'删除版块',
'Delete forum warning'			=>	'<strong>警告！</strong> 删除版块将同时彻底抹除该版块下的所有帖子',
'Edit forum'					=>	'编辑版块',
'Edit forum details legend'		=>	'版块详情',
'Category assignment'			=>	'所属分区',
'Forums in category'			=>	'当前分区下的版块：%s',
'Edit forum perms legend'		=>	'版块用户组权限（非默认权限将带有后缀 "(S)"）',
'Forum name label'				=>	'版块名称',
'Position label'				=>	'显示排序',
'Add to category label'			=>	'添加到分区',
'Forum description'				=>	'版块简介',
'Forum description help'		=>	'（简介内容支持使用 HTML 代码）',
'Sort topics by'				=>	'主题排序依据',
'Sort last post'				=>	'最后发表',
'Sort topic start'				=>	'发布时间',
'Redirect URL'					=>	'重定向跳转 URL',
'Only for empty forums'			=>	'仅在空版块中可用',
'Edit forums head'				=>	'编辑、删除或调整版块排序',
'Edit forum details head'		=>	'编辑版块信息',
'Edit forum perms head'			=>	'编辑版块权限',
'Post replies'					=>	'回复帖子',
'Post topics'					=>	'发布主题',
'User groups'					=>	'用户组',
'Confirm delete forum'			=>	'您正在删除版块 "%s"',
'Forum perms read info'			=>	'若相关用户组本身未开启“允许访问论坛”权限，则这里的“浏览版块”选框将无法勾选',
'Forum perms redirect info'		=>	'当前版块为外部链接跳转版块，因此仅有“浏览版块”权限可供编辑',
'Forum perms restore info'		=>	'点击下方的“恢复默认权限”按钮，可将所有权限配置重置为默认值',
'Forum perms groups info'		=>	'除非带有后缀 "(S)"，否则此处的权限均为 %s 中的默认全局设置',
'Forum perms admins info'		=>	'论坛管理员始终拥有完全管理权限，且不受此权限矩阵限制',
'Not default'					=>	'(S)',
'Read forum'					=>	'浏览&#160;版块',
'Restore defaults'				=>	'恢复默认权限',
'Add forum'						=>	'添加版块',
'Add forum head'				=>	'在指定分区的特定位置创建一个新版块',
'Add forum legend'				=>	'添加新版块',
'Add to category'				=>	'所属分区',
'Update positions'				=>	'更新版块排序',
'Forum added'					=>	'版块已成功添加',
'Forum deleted'					=>	'版块已成功删除',
'Forums updated'				=>	'版块排序已更新',
'Forum updated'					=>	'版块信息已更新',
'Permissions reverted'			=>	'版块权限已重置为默认设置',
'Must enter forum message'		=>	'请输入版块名称',

);