<?php

// 后台用户管理所使用的语言定义
// 简体中文 作者 reishi https://reishi.cc
$lang_admin_users = array(

// admin_users
'Search head'					=>	'查找会员',
'User search head'				=>	'请输入一个或多个检索条件，支持使用通配符 <strong>*</strong> 进行模糊匹配',
'Searches personal legend'		=>	'个人详细信息',
'Username label'				=>	'用户名',
'Title label'					=>	'专属头衔',
'Real name label'				=>	'真实姓名',
'Location label'				=>	'来自地区',
'Signature label'				=>	'个性签名',
'Admin note label'				=>	'管理员备注',
'Searches contact legend'		=>	'联系方式详情',
'E-mail address label'			=>	'电子邮箱地址',
'Website label'					=>	'个人网站',
'Searches activity legend'		=>	'用户活跃度',
'More posts label'				=>	'发帖量大于',
'Less posts label'				=>	'发帖量小于',
'Number of posts help'			=>	'（填写帖子总数）',
'Last post after label'			=>	'最后发帖时间晚于',
'Last post before label'		=>	'最后发帖时间早于',
'Registered after label'		=>	'注册时间晚于',
'Registered before label'		=>	'注册时间早于',
'Date format help'				=>	'[ 格式规范：yyyy-mm-dd hh:mm:ss ]',
'Jabber label'					=>	'Jabber',
'ICQ label'						=>	'ICQ',
'MSN Messenger label'			=>	'MSN Messenger',
'AOL IM label'					=>	'AOL IM',
'Yahoo Messenger label'			=>	'Yahoo! Messenger',
'User results head'				=>	'搜索结果排序规则',
'User results legend'			=>	'搜索结果配置',
'Order by label'				=>	'排序依据',
'Sort order label'				=>	'排列顺序',
'User group label'				=>	'所属用户组',
'IP search head'				=>	'在帖子数据库中查找指定的 IP 地址',
'IP search legend'				=>	'输入需要查询的 IP 地址',
'IP address label'				=>	'IP 地址',
'User information'				=>	'会员账号信息',
'IP address'					=>	'IP 地址',
'Username'						=>	'用户名',
'E-mail'						=>	'电子邮箱',
'Admin note'					=>	'管理员备注',

'Invalid IP address'			=>	'您输入的 IP 地址格式不正确',
'Users matching criteria'		=>	'符合筛选条件的用户列表',
'User IP stats'					=>	'该用户的 IP 历史统计数据',
'IP matching criteria'			=>	'匹配该 IP 地址的检索结果',
'Users found'					=>	'已找到匹配的用户 [ %s ]',
'IP addresses found'			=>	'已找到匹配的 IP 地址 [ %s ]',
'Moderate users'				=>	'管理这些用户',
'Submit search'					=>	'提交搜索',
'Not verified'					=>	'未验证激活',
'Registered'					=>	'注册时间',
'Last post'						=>	'最后发帖',
'Ascending'						=>	'升序',
'Descending'					=>	'降序',
'All groups'					=>	'所有用户组',
'Unverified users'				=>	'未验证激活的用户',
'Non numeric value message'		=>	'您在只能填写数字的输入框中输入了非数字内容',
'Invalid date/time message'		=>	'您输入的日期或时间格式不合法',
'No search terms message'		=>	'您没有输入任何搜索关键词或检索条件',
'Delete users'					=>	'删除选中的用户',
'Delete warning'				=>	'<strong>严重警告！</strong> 账号及帖子一旦被删除将永远无法恢复。如果您选择在删除账号的同时保留其历史发帖，这些帖子随后只能由管理员手动一条条去删除',
'Delete posts legend'			=>	'您可以自由选择是否一并清理这些用户发表过的帖子',
'Confirm delete'				=>	'确认执行删除',
'Delete posts'					=>	'同步删除历史发帖',
'Delete posts label'			=>	'勾选此项将彻底清除这些用户发布过的所有帖子和主题',
'Users deleted'					=>	'选中的用户已被成功删除',
'Ban'							=>	'封禁',
'Ban users'						=>	'封禁选中的用户',
'Change group'					=>	'变更用户组',
'Delete admin message'			=>	'系统强制保护：超级管理员账号无法被直接删除。如需删除该账号，必须先将其移出管理员组并归入其他普通用户组',
'Ban admin message'				=>	'在您选中的用户中包含超级管理员，无法对其执行封禁。若必须要封禁该账号，请先将其转移到其他普通用户组',
'Users banned'					=>	'选中的用户已被成功封禁',
'Mass ban info'					=>	'您可以为这些被封禁的用户设置一条统一展示的封禁提示语，并指定封禁的过期解除时间',
'Ban settings legend'			=>	'账号封禁设置',
'Change group head'				=>	'将选中的用户批量划分到新的用户组',
'User groups updated'			=>	'用户组信息已成功更新',
'Move users legend'				=>	'转移用户',
'No users selected'				=>	'您未选中任何用户',
'Move users to label'			=>	'将用户划归至目标组',

// admin_users tables
'Username column'				=>	'用户名 — 邮箱 — 管理员备注',
'Title column'					=>	'头衔 — 状态',
'Posts'							=>	'发帖数',
'Actions'						=>	'管理操作',
'View IP stats'					=>	'查看 IP 统计',
'Show posts'					=>	'查看发帖记录',
'Last used'						=>	'最后使用时间',
'Times found'					=>	'匹配次数',
'Find more users'				=>	'查找使用过该 IP 的其他用户',
'No posts by user'				=>	'该用户目前在论坛中没有发表过任何帖子',
'Guest'							=>	'游客',
'Cannot find IP'				=>	'在当前的帖子数据库中未检索到您提供的 IP 地址',
'Not verified'					=>	'未验证激活',
'No match'						=>	'未找到匹配项',
'User search results'			=>	'用户检索结果'

);