<?php

// 后台用户组管理所使用的语言定义
// 简体中文 作者 reishi https://reishi.cc
$lang_admin_groups = array(

// admin_groups
'Group settings heading'		=>	'当未单独配置版块特定权限时所适用的用户组默认全局权限',
'Group title label'				=>	'用户组名称',
'User title label'				=>	'用户专属头衔',
'Group title head'				=>	'用户组及用户头衔设置',
'Group title legend'			=>	'设置名称与头衔',
'Group perms head'				=>	'用户组权限',
'Group flood head'				=>	'用户组防灌水刷屏限制',
'User title help'				=>	'此专属头衔将覆盖该组用户通过积分等级获得的专属等级头衔。留空则默认使用系统自带的用户组名称或等级头衔',
'Remove group legend'			=>	'删除用户组',
'Permissions'					=>	'权限管理',
'Moderation'					=>	'版主权限',
'Allow moderate label'			=>	'允许该组用户获得版主管理权限',
'Allow mod edit profiles label'	=>	'允许版主修改其他用户的个人资料',
'Allow mod edit username label'	=>	'允许版主修改其他用户的用户名',
'Allow mod change pass label'	=>	'允许版主修改其他用户的登录密码',
'Allow mod bans label'			=>	'允许版主封禁用户',
'Allow read board label'		=>	'允许用户访问并浏览论坛',
'Allow read board help'			=>	'此选项属于全局底层开关。如果关闭，即使版块单独开启了允许浏览权限也无法覆盖。关闭后该组用户将仅能进行登录、退出及注册操作',
'Allow view users label'		=>	'允许用户查看用户列表及他人个人资料页面',
'Allow post replies label'		=>	'允许用户在主题下发表回复',
'Allow post topics label'		=>	'允许用户发布新主题',
'Allow edit posts label'		=>	'允许用户编辑自己发表的帖子',
'Allow delete posts label'		=>	'允许用户删除自己发表的帖子',
'Allow delete topics label'		=>	'允许用户删除自己发布的主题（包含主题下的所有回复）',
'Allow set user title label'	=>	'允许用户自定义个性化专属头衔',
'Allow use search label'		=>	'允许用户使用论坛内置的搜索功能',
'Allow search users label'		=>	'允许用户在用户列表中通过关键字搜索其他会员',
'Allow send email label'		=>	'允许用户向其他会员发送电子邮件',
'Restrictions'					=>	'频率限制',
'Mod permissions'				=>	'版主权限控制',
'User permissions'				=>	'常规用户权限',
'Flood interval label'			=>	'发帖防灌水时间间隔',
'Flood interval help'			=>	'该组用户两次发帖或回复之间所需等待的秒数。设为 0 则不限制发帖频率',
'Search interval label'			=>	'搜索防刷屏时间间隔',
'Search interval help'			=>	'该组用户两次搜索操作之间所需等待的秒数。设为 0 则不限制搜索频率',
'Email flood interval label'	=>	'邮件发送防刷屏时间间隔',
'Email flood interval help'		=>	'该组用户两次发送邮件之间所需等待的秒数。设为 0 则不限制邮件发送频率',
'Allow moderate help'			=>	'为了使该组会员真正获得版主管理权限，您必须在用户的个人资料管理页面中，为其指派具体负责管理的一个或多个版块',
'Remove group'					=>	'删除当前用户组',
'Edit group'					=>	'编辑当前用户组',
'default'						=>	'（默认）',
'Cannot remove group'			=>	'当前用户组无法被删除',
'Cannot remove default'			=>	'在删除当前用户组之前，您必须先将另一个用户组设为系统默认用户组',
'Remove group head'				=>	'删除包含 %s 名成员的 "%s" 用户组',
'Remove group help'				=>	'（将当前组内的成员全部转移至该组）',
'Move users to'					=>	'将现有成员转移至',
'Cannot remove default group'	=>	'系统默认用户组无法直接删除。若要强制删除该组，必须先将另一个其他用户组指定为新用户注册时的默认组',
'Add group heading'				=>	'添加新用户组（新组将自动继承其基准用户组的所有权限）',
'Add group legend'				=>	'添加新用户组',
'Edit group heading'			=>	'编辑现有用户组',
'Base new group label'			=>	'继承哪个组的权限',
'Add group'						=>	'添加用户组',
'Default group heading'			=>	'新注册用户的默认归属组（出于安全考虑，无法在此选择管理员组或版主组）',
'Default group legend'			=>	'配置新用户默认归属组',
'Default group label'			=>	'默认用户组',
'Set default'					=>	'设为默认用户组',
'Existing groups heading'		=>	'现有用户组列表',
'Existing groups intro'			=>	'系统预设的游客组与管理员组无法被删除，但允许进行编辑修改。需要注意的是，在某些特定组中部分权限选项是强制锁定的（例如游客组无法开启编辑帖子权限）。管理员组则始终拥有最高全权',
'Group removed'					=>	'用户组已成功删除',
'Default group set'				=>	'默认用户组已成功设置',
'Group added'					=>	'用户组已成功添加',
'Group edited'					=>	'用户组信息已成功更新',
'Update group'					=>	'更新用户组',
'Must enter group message'		=>	'请输入用户组名称',
'Already a group message'		=>	'已经存在名为 <strong>"%s"</strong> 的用户组',
'Moderator default group'		=>	'该组目前是新用户的系统默认归属组，因此无法直接赋予其版主管理特权',

);