<?php

// 后台扩展与补丁管理所使用的语言定义
// 简体中文 作者 reishi https://reishi.cc
$lang_admin_ext = array(

'Install extension'				=>	'安装扩展',
'Upgrade extension'				=>	'升级扩展',
'Extensions available'			=>	'可供安装的扩展',
'Hotfixes available'			=>	'可供安装的热补丁',
'Installed extensions'			=>	'已安装的扩展',
'Version'						=>	'版本号 "%s"',
'Hotfix'						=>	'热补丁',
'Installed hotfixes'			=>	'已安装的热补丁',
'Installed extensions warn'		=>	'<strong>警告！</strong> 卸载扩展将会永久删除该扩展在数据库中的所有关联数据，且无法通过重新安装来恢复。如果您希望保留数据，请选择“禁用”而非“卸载”',
'Uninstall extension'			=>	'卸载扩展',
'Uninstall hotfix'				=>	'卸载热补丁',
'Uninstall'						=>	'卸载',
'Uninstall extension confirm'	=>	'您确定要卸载扩展 "%s" 吗',
'Enable'						=>	'启用',
'Disable'						=>	'禁用',
'Extension error'				=>	'错误',
'Extension loading error'		=>	'加载扩展 "%s" 失败',
'Illegal ID'					=>	'ID 只能包含小写字母、数字（a-z，0-9）以及下划线（_）',
'Maxtestedon error'				=>	'此扩展与您当前的 PunBB 版本不兼容',
'Maxtestedon warning'			=>	'此扩展未在您当前的 PunBB 版本上进行过完整测试，可能存在不兼容的风险',
'Missing manifest'				=>	'缺少 manifest.xml 配置文件',
'Failed parse manifest'			=>	'无法解析 manifest.xml 配置文件',
'extension root error'			=>	'根元素 extension 格式错误或缺失',
'extension/engine error'		=>	'根元素的 engine 属性格式错误或缺失',
'extension/engine error2'		=>	'不支持该扩展的格式版本',
'extension/id error'			=>	'extension/id 元素格式错误或缺失',
'extension/id error2'			=>	'extension/id 元素与扩展文件夹名称不匹配',
'extension/title error'			=>	'extension/title 元素格式错误或缺失',
'extension/version error'		=>	'extension/version 元素格式错误或缺失',
'extension/description error'	=>	'extension/description 元素格式错误或缺失',
'extension/author error'		=>	'extension/author 元素格式错误或缺失',
'extension/minversion error'	=>	'extension/minversion 元素格式错误或缺失',
'extension/minversion error2'	=>	'此扩展需要 PunBB "%s" 或更高版本支持',
'extension/maxtestedon error'	=>	'extension/maxtestedon 元素格式错误或缺失',
'extension/note error'			=>	'extension/note 元素格式错误',
'extension/note error2'			=>	'extension/note 元素的 "type" 属性格式错误或缺失',
'extension/hooks/hook error'	=>	'extension/hooks/hook 元素格式错误或缺失',
'extension/hooks/hook error2'	=>	'extension/hooks/hook 元素缺少 "id" 属性',
'extension/hooks/hook error3'	=>	'extension/hooks/hook 元素的 "priority" 属性值超出正常范围',
'extension/hooks/hook error4'	=>	'extension/hooks/hook 元素中的内容未正确以 PHP 模式结束',
'No XML support'				=>	'当前的 PHP 环境未内置 XML 支持。运行 PunBB 扩展必须开通 XML 支持，请参考 PHP 官方文档进行配置',
'No installed extensions'		=>	'当前未安装任何扩展',
'No installed hotfixes'			=>	'当前未安装任何热补丁',
'No available extensions'		=>	'暂无可安装或升级的扩展',
'No available hotfixes'			=>	'暂无可安装的热补丁',
'Invalid extensions'			=>	'<strong>重要提示！</strong> 在扩展目录中找到了下列扩展，但由于检测到相应错误，它们目前无法进行安装或升级',
'Extension installed'			=>	'扩展安装成功',
'Hotfix installed'				=>	'热补丁安装成功',
'Extension installed info'		=>	'扩展已成功安装，但有以下提示信息',
'Extension uninstalled'			=>	'扩展已成功卸载',
'Hotfix uninstalled'			=>	'热补丁已成功卸载',
'Extension uninstalled info'	=>	'扩展已成功卸载，但有以下提示信息',
'Install note'					=>	'安装前请仔细阅读',
'Uninstall note'				=>	'卸载前请仔细阅读',
'Hotfix download failed'		=>	'热补丁下载并安装失败，请稍后重试',
'Extension disabled'			=>	'扩展已禁用',
'Extension enabled'				=>	'扩展已启用',
'Hotfix disabled'				=>	'热补丁已禁用',
'Hotfix enabled'				=>	'热补丁已启用',
'Extension by'					=>	'开发者静态："%s"',
'Hotfix description'			=>	'自动更新检测到适用于您当前 PunBB 系统的热补丁',
'Install hotfix'				=>	'安装热补丁',
'Missing dependency'			=>	'由于必须先安装并启用扩展 "%s"，此扩展目前无法安装',
'Uninstall dependency'			=>	'由于扩展 "%s" 依赖此项目，目前无法卸载',
'Disable dependency'			=>	'由于扩展 "%s" 处于启用状态，目前无法禁用此项目',
'Disabled dependency'			=>	'由于扩展 "%s" 处于禁用状态，目前无法启用此项目',
'Download latest version'		=>	'下载最新版本',
'Version dependency error'		=>	'扩展 "%s" 的版本必须为 "%s" 或更高',
'Install ext errors'			=>	'<strong>警告！</strong> 在安装该扩展前，必须先修正以下错误',

);