<?php

// 版块列表页面所使用的语言定义
// 简体中文 作者 reishi https://reishi.cc
$lang_forum = array(

'Forum subtitle'			=>	'当前版块内的 %1$s 以及 %2$s 的详细信息',
'Search subtitle'			=>	'已找到匹配的 %1$s 以及 %2$s 的详细信息',
'Topics'					=>	'主题数',
'topics'					=>	'主题',
'Reply'						=>	'回复数',
'Replies'					=>	'回复数',
'Forum'						=>	'版块',
'reply'						=>	'回复',
'replies'					=>	'回复',
'View'						=>	'浏览数',
'Views'						=>	'浏览数',
'views'						=>	'浏览',
'view'						=>	'浏览',
'Last post'					=>	'最后发表',
'last post'					=>	'最后发表',
'Select topic'				=>	'选择主题：%s',
'No replies info'			=>	'暂无回复信息',
'No views info'				=>	'暂无浏览信息',
'No lastpost info'			=>	'暂无最后发表信息',
'by poster'					=>	'由 %s 发表',
'Item status'				=>	'%s：',
'Topic starter'				=>	'由 <cite>%s</cite> 发起',
'New posts'					=>	'有新回复',
'Topic navigation'			=>	'（ %s ）',
'Location'					=>	'所在版块：%s',
'Pages'						=>	'页码',
'Post topic'				=>	'发表新主题',
'Login to post'				=>	'您必须先 %1$s 或 %2$s 才能发表新主题',
'No permission'				=>	'抱歉，您没有在本版块发表新主题的权限',
'Moved'						=>	'已移动',
'Sticky'					=>	'置顶',
'Closed'					=>	'已关闭',
'Empty forum'				=>	'空版块',
'No topics'					=>	'当前版块内暂无任何主题',
'First topic nag'			=>	'快来抢沙发，发布本版块的第一条主题吧',
'You posted indicator'		=>	'·',
'Permalink forum'			=>	'本版块的永久链接',
'Forum options'				=>	'版块管理选项',
'Moderate forum'			=>	'管理本版块',
'Mark forum read'			=>	'标记本版块为已读',
'RSS forum feed'			=>	'本版块的 RSS 订阅源',
'New posts info'			=>	'跳转至您上次访问以来的第一条新回复',
'Unsubscribe'				=>	'取消关注',
'Subscribe'					=>	'关注本版',
'Subscribe info'			=>	'当本版块有新主题发布时接收电子邮件通知',

);