<?php

// 安装引导程序所使用的语言定义
// 简体中文 作者 reishi https://reishi.cc
$lang_install = array(

// 安装表单
'Install PunBB'				=>	'安装 PunBB %s',
'Choose language'			=>	'切换安装向导语言',
'Choose language help'		=>	'如果您觉得使用母语阅读安装说明更方便，可以在下方已安装的语言包列表中选择切换向导的显示语言',
'Installer language'		=>	'向导语言：',
'Choose language legend'	=>	'安装向导语言',
'Install intro'				=>	'在安装 PunBB 之前，您必须填写完下方的配置表单。请在填写前仔细阅读各项说明。如果您在安装过程中遇到任何困难，请参阅 PunBB 源码压缩包中附带的官方文档',
'Part1'						=>	'步骤 1 — 数据库配置',
'Part1 intro'				=>	'请输入相关配置信息以建立 PunBB 所需的数据库连接。在继续安装之前，您必须明确以下所有必备信息。本表单各输入项的具体填写帮助已在下方列出',
'Database type'				=>	'数据库类型',
'Database name'				=>	'数据库名称',
'Database server'			=>	'数据库服务器地址',
'Database username'			=>	'数据库用户名',
'Database password'			=>	'数据库密码',
'Database user pass'		=>	'数据库账号与密码',
'Table prefix'				=>	'数据表前缀',
'Database type info'		=>	'PunBB 目前支持 MySQL、PostgreSQL 和 SQLite。如果下方下拉菜单中没有您想选的数据库，说明您当前的 PHP 运行环境未加载该数据库的扩展组件。有关各数据库特定版本的支持详情，请参阅 FAQ 常见问题解答',
'Mysql type info'			=>	'PunBB 检测到您的 PHP 环境支持两种与 MySQL 通信的方式。这两项配置分别称为“<em>标准版驱动 (mysql)</em>”和“<em>增强版驱动 (mysqli)</em>”。如果您拿不准该选哪一个，建议优先尝试增强版驱动，如果连接失败再切回标准版',
'Database server info'		=>	'请输入数据库服务器的访问地址（例如：<em>localhost</em>、<em>mysql1.example.com</em> 或 <em>208.77.188.166</em>）。如果您的数据库没有运行在默认端口上，您可以加上自定义端口号（例如：<em>localhost:3580</em>）。如果使用 SQLite 数据库，此处可随意填写或保持默认的 “localhost”',
'Database name info'		=>	'请输入准备用于安装 PunBB 的数据库名称。该数据库必须已经提前创建好。对于 SQLite，此处需填写指向数据库文件的相对路径。如果该 SQLite 文件不存在，PunBB 将尝试自动创建它',
'Database username info'	=>	'请输入连接至所选数据库所需的用户名和密码。若使用 SQLite 请忽略此项',
'Table prefix info'			=>	'选填 — 请输入数据表前缀。通过指定不同的前缀，您可以在同一个数据库中运行多个独立的 PunBB 论坛实例（例如：<em>foo_</em>）',
'Part1 legend'				=>	'数据库连接信息',
'Database type help'		=>	'选择您的数据库类型',
'Database server help'		=>	'数据库服务器的访问地址，SQLite 请随便填写',
'Database name help'		=>	'准备用于安装 PunBB 的现有数据库',
'Database username help'	=>	'用于数据库连接的账号，SQLite 请忽略',
'Database password help'	=>	'用于数据库连接的密码，SQLite 请忽略',
'Table prefix help'			=>	'选填的数据表前缀，例如 “foo_”',
'Part2'						=>	'步骤 2 — 论坛超级管理员配置',
'Part2 legend'				=>	'管理员账号详情',
'Part2 intro'				=>	'请设置您的 PunBB 超级管理员账号信息。安装完成后，您可以在后台随时创建更多的管理员或版主账号',
'Admin username'			=>	'管理员用户名',
'Admin password'			=>	'管理员密码',
'Admin confirm password'	=>	'确认新密码',
'Admin e-mail'				=>	'管理员电子邮箱',
'Username help'				=>	'长度须在 2 到 25 个字符之间',
'Password help'				=>	'长度至少为 4 个字符，且严格区分大小写',
'Confirm password help'		=>	'请再次输入完全相同的密码',
'E-mail address help'		=>	'用于接收系统通知及管理的管理员有效电子邮箱地址',
'Part3'						=>	'步骤 3 — 论坛基本设置',
'Part3 legend'				=>	'论坛全局信息',
'Part3 intro'				=>	'请输入论坛的基本信息。请务必格外注意检查您的站点根路径网址，并仔细阅读下方的填写说明',
'Base URL'					=>	'站点根路径网址 (Base URL)',
'Base URL info'				=>	'在输入站点根路径网址时请务必格外留神。如果此项配置错误，您的论坛前后台将无法正常运作。根路径网址是指您的 PunBB 论坛所在的完整 URL（结尾不要加斜杠 /）（例如：<em>http://forum.example.com</em> 或 <em>http://example.com/~myuser</em>）。请注意，下方预填的数值只是系统根据环境进行的常规推测',
'Base URL help'				=>	'您的 PunBB 安装目录所对应的完整 URL 网址（结尾切勿加斜杠）',
'Pun repository'			=>	'应用扩展仓库',
'Pun repository help'		=>	'勾选此项将在论坛安装完毕后同步安装 pun_repository 扩展组件（一键下载扩展插件助手）',
'Start install'				=>	'开始执行安装', // Label for submit button
'Required'					=>	'（必填）',
'Required warn'				=>	'在提交表单前，所有加粗显示标签的输入框都必须填写完整',

// 安装错误提示
'No database support'		=>	'当前 PHP 运行环境未检测到任何 PunBB 所支持的数据库组件。必须启用 MySQL、PostgreSQL 或 SQLite 中的至少一种，才能继续安装 PunBB',
'Missing database name'		=>	'您必须输入数据库名称，请返回修改',
'Username too long'			=>	'管理员用户名长度不能超过 25 个字符，请返回修改',
'Username too short'		=>	'管理员用户名长度至少需要 2 个字符，请返回修改',
'Pass too short'			=>	'密码长度至少需要 4 个字符，请返回修改',
'Username guest'			=>	'用户名 guest 为系统保留字，请返回修改',
'Username BBCode'			=>	'用户名中不能包含任何论坛所使用的文本格式化标签（BBCode），请返回修改',
'Username reserved chars'	=>	'用户名中不能同时包含单引号、双引号以及中括号 [ 或 ]，请返回修改',
'Username IP'				=>	'用户名不能采用 IP 地址的形式，请返回修改',
'Invalid email'				=>	'您输入的管理员电子邮箱地址格式不合法，请返回修改',
'Missing base url'			=>	'您必须输入站点根路径网址，请返回修改',
'No such database type'		=>	'“%s” 不是合法的数据库类型',
'Invalid MySQL version'		=>	'当前服务器的 MySQL 版本为 %1$s。PunBB 至少需要 MySQL %2$s 才能正常运作。您必须先升级 MySQL 数据库后才能继续安装',
'Invalid table prefix'		=>	'您设置的数据表前缀 “%s” 包含非法字符或长度超限。前缀只能由字母 a-z、数字以及下划线组成，且不能以数字开头，最大长度限制为 40 个字符，请选择其他前缀',
'SQLite prefix collision'	=>	'数据表前缀 “sqlite_” 已被 SQLite 核心引擎强制保留占用，请选择其他前缀',
'PunBB already installed'	=>	'数据库 “%2$s” 中已存在名为 “%1$susers” 的数据表。这表明 PunBB 可能已经安装过，或者有其他程序占用了 PunBB 所需的表名。如果您想在同一个数据库中安装多个 PunBB 实例，必须换一个不同数据表前缀',
'Invalid language'			=>	'您选择的语言包似乎不存在或已损坏，请重新检查并重试',
'InnoDB Not Supported'		=>	'您当前的 MySQL 版本不支持或未开启 InnoDB 存储引擎',

// 安装预设初始数据
'Default language'			=>	'默认语言',
'Default language help'		=>	'（如果您以后删除了某个语言包，请记得同步更新此项设置）',
'Default announce heading'	=>	'示例系统公告',
'Default announce message'	=>	'<p>请在此处输入您的全局系统公告内容</p>',
'Default rules'				=>	'请在此处输入您的论坛服务协议与站规条例',
'Default category name'		=>	'测试分区',
'Default forum name'		=>	'测试版块',
'Default forum descrip'		=>	'这只是一个用于系统安装测试的默认版块',
'Default topic subject'		=>	'测试首帖',
'Default post contents'		=>	'如果您能看到这条内容（我想您正看着它），说明您的 PunBB 论坛已经成功安装完毕。现在您可以登录账号并前往管理员控制面板来配置您的站点了',
'Default rank 1'			=>	'初来乍到',
'Default rank 2'			=>	'正式会员',


// 安装成功页面
'Success description'		=>	'恭喜。PunBB %s 已成功安装完成',
'Final instructions'		=>	'最后一步后续操作说明',
'No write info 1'			=>	'重要提示！为完成最后的建站配置，您需要点击下方的按钮下载名为 config.php 的配置文件。然后您需要将该文件手动上传到 PunBB 论坛的根目录下',
'No write info 2'			=>	'一旦您成功上传了 config.php 文件，PunBB 随即彻底安装完成。上传就绪后，您可以点击此处 %s',
'Go to index'				=>	'前往论坛首页',
'Warning'					=>	'严重警告！',
'No cache write'			=>	'<strong>缓存目录当前不可写！</strong> 为了能让 PunBB 正常运行，名为 <em>cache</em> 的目录必须赋予 PHP 写入权限。请使用 chmod 命令调整该目录的权限。如果不确定，请将其设置为 0777',
'No avatar write'			=>	'<strong>头像目录当前不可写！</strong> 如果您希望会员能上传自定义头像，必须确保名为 <em>img/avatars</em> 的目录对 PHP 可写。您稍后也可以在后台选择将头像保存在其他路径（参见：全局管理/常规设置/功能配置）。请使用 chmod 命令调整目录权限。如果不确定，请将其设置为 0777',
'File upload alert'			=>	'<strong>当前服务器似乎禁止了文件上传功能！</strong> 如果您需要开启会员头像上传，必须在服务器的 PHP 配置中将 file_uploads 选项设为开启状态。开启后，方可在后台的全局管理/常规设置/功能配置中激活头像上传',
'Download config'			=>	'下载 config.php 配置文件', // Label for submit button
'Write info'				=>	'PunBB 已经全部安装就绪。您现在可以 %s',
);