<?php

// 搜索功能页面所使用的语言定义
// 简体中文 作者 reishi https://reishi.cc
$lang_search = array(

// 搜索表单
'No search permission'		=>	'您当前没有权限使用论坛的搜索功能',
'Search heading'			=>	'输入检索条件筛选论坛内容',
'Search flood'				=>	'两次搜索之间至少需要间隔 %s 秒，请稍等片刻后再试',
'Search legend'				=>	'检索条件配置',
'Results legend'			=>	'搜索结果展现',
'Keywords info'				=>	'您可以输入单个关键词，或者输入多个关键词并用空格隔开进行多词检索',
'Refine info'				=>	'您可以在关键词之间使用 <strong>AND</strong>、<strong>OR</strong> 或 <strong>NOT</strong> 来执行更高级的逻辑组合筛选',
'Wildcard info'				=>	'支持使用通配符 <strong>*</strong> 进行模糊匹配，适用于部分关键词或特定会员昵称的模糊检索',
'Forum default info'		=>	'系统默认会检索所有版块的内容，您也可以通过多选操作来缩小检索的版块范围',
'Forum require info'		=>	'您可以指定在任意一个或多个版块中查找，但您 <strong>必须</strong> 至少选中一个版块',
'Keyword search'			=>	'关键词',
'Author search'				=>	'发贴人昵称',
'Forum search'				=>	'选择目标版块',
'Forum search default'		=>	'如果您未选中任何特定版块，系统将默认在全站所有版块中执行搜索',
'Forum search require'		=>	'请至少选择一个目标版块进行检索',
'Sort by'					=>	'结果排序依据',
'Sort order'				=>	'结果排序规则',
'Sort by post time'			=>	'发布时间',
'Sort by author'			=>	'发布作者',
'Sort by subject'			=>	'主题标题',
'Sort by forum'				=>	'所属版块',
'Ascending'					=>	'正序 (旧帖在前)',
'Descending'				=>	'倒序 (新帖在前)',
'Display results'			=>	'结果呈现方式',
'Show as topics'			=>	'按主题列表聚合展示',
'Show as posts'				=>	'按帖子正文平铺展示',
'Submit search'				=>	'立即执行搜索',
'User defined search'		=>	'自定义条件搜索',
'Advanced search'			=>	'高级搜索控制台',
'Search in'					=>	'检索匹配范围',
'Message and subject'		=>	'同时匹配帖子正文与主题标题',
'Message only'				=>	'仅匹配帖子正文内容',
'Topic only'				=>	'仅匹配主题标题',

// 搜索结果
'Search results'			=>	'搜索结果',
'Topics with new'			=>	'包含新回复的主题',
'All Topics'				=>	'展示所有主题',
'Recently active topics'	=>	'近期活跃的主题',
'Unanswered topics'			=>	'暂无回复的主题',
'Subscriptions'				=>	'我关注的主题订阅',
'Forum subscriptions'		=>	'我订阅的版块动态',
'Forums found'				=>	'检索到的版块数',
'Topics found'				=>	'检索到的主题数',
'Posts found'				=>	'检索到的帖子数',
'Topics by'					=>	'由 %s 发表的主题',
'Posts by'					=>	'由 %s 发表的帖子',
'Topics by user'			=>	'该会员发表的所有主题',
'Posts by user'				=>	'该会员发表的所有帖子',
'Perform new search'		=>	'发起新的搜索',
'Search options'			=>	'检索附加选项',
'Posted in'					=>	'发表于 ',
'No terms'					=>	'您必须输入至少一个关键词或者指定一位发贴人昵称才能执行搜索',
'No hits'					=>	'未检索到任何符合条件的条目',
'No user posts'				=>	'当前版块内没有找到该会员发表的帖子',
'No user topics'			=>	'当前版块内没有找到该会员发起的主题',
'No subscriptions'			=>	'您的主题关注列表中目前没有任何内容',
'No forum subscriptions'	=>	'您的版块订阅列表中目前没有任何内容',
'No new posts'				=>	'自您上次访问以来，论坛中还没有出现包含新回复的主题',
'No recent posts'			=>	'论坛近期内尚无任何新发贴',
'No unanswered'				=>	'当前版块内不存在零回复的主题',
'Go to post'				=>	'直达该帖',
'Go to forum'				=>	'进入该版块',
'Go to topic'				=>	'进入该主题',
'Go to profile'				=>	'查看 %s 的个人资料'

);